### ISSUE TITLE
How to disaggregate quarterly series to weekly

### ISSUE THREAD

**Issue by vikaskumar30** [christophsax/tempdisagg#38]
Hi,
I am getting the following error when calling the td function in the below code
Error: time column needs to specified as the first date of the period
```
rm(list=ls())
library(quantmod)
library(tempdisagg)
library(readxl)

# Qtrly series
data<-read_excel("qtrly_series.xlsx", sheet = 1, col_names = c("Date","Value"), col_types = c("date","numeric"))
data_cs_ts<-as.xts(data$Value,order.by=as.Date(data$Date))

# Weekly series
data<-read_excel("weekly_series.xlsx", sheet = 1, col_names = c("Date","Value"), col_types = c("date","numeric"))
data_30y_ts<-as.xts(data$Value,order.by=as.Date(data$Date))

# Interpolating qtrly to weekly series 
interp_fit=td(data_cs_ts~data_30y_ts,conversion="average",to=13,method="chow-lin-maxlog")
data_mir<-as.xts(predict(interp_fit),order.by=as.Date(index(data_30y_ts)))
```
[qtrly_series.xlsx](https://github.com/christophsax/tempdisagg/files/3576328/qtrly_series.xlsx)
[weekly_series.xlsx](https://github.com/christophsax/tempdisagg/files/3576329/weekly_series.xlsx)

**Comment by vikaskumar30** [comment]
Hi @christophsax 
just bumping this again.

**Comment by christophsax** [comment]
If you use timestamp based time series within tempdisagg, the date column/index must to specified as the first day in the period. If you have quarterly data, it must be the first day of the quarter.

Weekly and quarterly data overlap each other. In order to make this work, you need to make your
weekly series daily first, then use the daily series as an indicator for the quarterly series. Finally, aggregate the daily series back to week. Here is how it can be done:

``` r
library(tidyverse)
library(tsbox)
library(tempdisagg)

y_q <- readxl::read_excel("qtrly_series.xlsx", col_names = c("time", "value")) %>%
  mutate(time = as.Date(time)) %>%
  tsbox:::ts_first_of_period()
x_w <- readxl::read_excel("weekly_series.xlsx", col_names = c("time", "value")) %>%
  mutate(time = as.Date(time)) %>%
  tsbox:::ts_first_of_period()
```

Make your weekly series daily first. You can do this like that:

``` r
m_1 <- td(x_w ~ 1, to = "day", method = "fast")
x_d <- predict(m_1)
x_d
#> # A tibble: 10,836 x 2
#>    time       value
#>    <date>     <dbl>
#>  1 1990-01-01  1.39
#>  2 1990-01-02  1.39
#>  3 1990-01-03  1.39
#>  4 1990-01-04  1.39
#>  5 1990-01-05  1.39
#>  6 1990-01-06  1.40
#>  7 1990-01-07  1.40
#>  8 1990-01-08  1.40
#>  9 1990-01-09  1.40
#> 10 1990-01-10  1.40
#> # … with 10,826 more rows
```

`fast` means faster than the other methods, but week to day is still really
slow. Be patient.
In a second step, you can disaggregate your quarterly series to daily
(which is faster):

``` r
m_2 <- td(y_q ~ x_d, method = "fast", conversion = "mean")
y_d <- predict(m_2)
y_d
#> # A tibble: 10,836 x 2
#>    time       value
#>    <date>     <dbl>
#>  1 1990-01-01  10.0
#>  2 1990-01-02  10.0
#>  3 1990-01-03  10.0
#>  4 1990-01-04  10.0
#>  5 1990-01-05  10.0
#>  6 1990-01-06  10.0
#>  7 1990-01-07  10.0
#>  8 1990-01-08  10.0
#>  9 1990-01-09  10.0
#> 10 1990-01-10  10.0
#> # … with 10,826 more rows
```

`y_d` can be aggregated to weekly again:

``` r
y_w <-
  y_d %>%
  group_by(
    time = as.Date(
      paste(lubridate::year(time), lubridate::week(time), 7),
      format = "%Y %U %u"
    ) - 6
  ) %>%
  summarize(value = mean(value)) %>%
  ungroup() %>%
  filter(!is.na(time))  # NA at the end

ts_plot(y_w, y_q)
```

![](https://i.imgur.com/7nUvK7s.png)

<sup>Created on 2019-09-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
